apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.service.externalServicePort }}
      targetPort: {{ .Values.service.internalServicePort }}
      protocol: TCP
      name: {{ .Values.service.name }}-srvc
    - port: {{ .Values.service.externalDockerStagingPort }}
      targetPort: {{ .Values.service.internalDockerStagingPort }}
      protocol: TCP
      name: {{ .Values.service.name }}-docker-staging
    - port: {{ .Values.service.externalDockerProdPort }}
      targetPort: {{ .Values.service.internalDockerProdPort }}
      protocol: TCP
      name: {{ .Values.service.name }}-docker-prod
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
