apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      # - name: jenkins-volume
      #   emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
            - containerPort: {{ .Values.service.internalJnplPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 5
          resources:
          # volumeMounts:
          # - mountPath: /var/jenkins_home
          #   name: jenkins-volume
          env:
          - name: NUMBER_OF_JENKINS_EXECUTORS
            value: {{ .Values.variables.numberOfExecutors }}
          - name: JAVA_MAX_HEAP
            value: {{ .Values.variables.javaMaxHeap }}
          - name: JAVA_MIN_HEAP
            value: {{ .Values.variables.javaMinHeap }}
          - name: JENKINS_ADMIN_PASSWORD
            value: {{ .Values.variables.jenkinsAdminPassword }}
          - name: GIT_USER_NAME
            value: {{ .Values.variables.gitUserName }}
          - name: GIT_USER_EMAIL
            value: {{ .Values.variables.gitUserEmail }}
          - name: PLUGINS_FILE_URL
            value: {{ .Values.variables.jenkinsPluginsFileUrl }}
          - name: PROJECT_LIST_FILE_URL
            value: {{ .Values.variables.jenkinsProjectsFileUrl }}
          - name: SSH_KEY_FILES_TAR_GZ_URL
            value: {{ .Values.variables.jenkinsSSHArchiveUrl }}
          - name: JENKINS_NODE_LIST_URL
            value: {{ .Values.variables.jenkinsAgentListFileUrl }}
          - name: SONARQUBE_URL
            value: {{ .Values.variables.jenkinsSonarqubeUrl }}
          - name: SONARQUBE_APIKEY
            value: {{ .Values.variables.jenkinsSonarqubeApiKey }}
          - name: SONARQUBE_USER
            value: {{ .Values.variables.jenkinsSonarqubeUserName }}
          - name: SONARQUBE_PASSWORD
            value: {{ .Values.variables.jenkinsSonarqubeUserPassword }}
          - name: NEXUS_BASE_URL
            value: {{ .Values.variables.jenkinsNexusUrl }}
          - name: NEXUS_SNAPSHOT_REPO_URL
            value: {{ .Values.variables.jenkinsNexusSnapshotUrl }}
          - name: NEXUS_RELEASE_REPO_URL
            value: {{ .Values.variables.jenkinsNexusReleaseUrl }}
          - name: NEXUS_STAGING_DOCKER_REPO_URL
            value: {{ .Values.variables.jenkinsNexusDockerStagingUrl }}
          - name: NEXUS_PRODUCTION_DOCKER_REPO_URL
            value: {{ .Values.variables.jenkinsNexusDockerProductionUrl }}
          - name: NEXUS_USER
            value: {{ .Values.variables.jenkinsNexusUserName }}
          - name: NEXUS_PASSWORD
            value: {{ .Values.variables.jenkinsNexusUserPassword }}
          securityContext:
            privileged: true
            capabilities:
              add:
              - IPC_LOCK
              - SYS_ADMIN
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
